spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path= /contact/**
          filters:
            - AuthenticationFilter

        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path= /feedback/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8383