eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8383



spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - POST
              - GET
              - PUT
              - DELETE
            allowed-headers:
              - Authorization
              - Content-Type
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials

      routes:
        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path= /contact/**
          filters:
            - AuthenticationFilter

        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path= /feedback/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path= /identity/**
          filters:
            - AuthenticationFilter


